baseURL = "https://vflins.github.io/"
languageCode = "pt_BR"
defaultContentLanguage = "pt-br"
title = "Vitor F. Lins"
theme = ["ananke"]
sectionPagesMenu = "main"
enableEmoji = true

[params]
date_format = ":date_full"
locale = "pt_BR"
read_more_copy = "continue lendo"
custom_css = ["colors.css", "layout.css"]
background_color_class = "bg-dark-green"
formspree_id = "maqwnkzg"

[taxonomies]
tag = "tags"
category = "categories"

[params.ananke.social.share]
icons = true
networks = ["email", "facebook", "instagram", "linkedin", "whatsapp"]

[params.ananke.social.linkedin]
username = "vflins"

[params.ananke.social.instagram]
username = "vitorkon"

[params.ananke.social.medium]
username = "vflins"

[params.ananke.social.github]
username = "VFLins"

[params.ananke.social.follow]
new_window_icon = true
networks = ["instagram", "medium", "github"]

[markup.highlight]
style = "trac"

[markup.goldmark.parser.attribute]
block = true
